### ISSUE TITLE
v0.8.6.1107 doesn't work with Ventura.

### ISSUE THREAD

**Issue by ghost** [hackintosh-club/intel-nuc10#89]
I updated Monterey to Ventura and received a prohibitory symbol when using the 0.8.6 EFI.

What works is 0.8.4 efi with just the AirportItlwm.kext from 0.8.6 EFI.

https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macos/Big-Sur/macos-big-sur-startup-screen-prohibitory-sign.jpg

**Comment by vuqn1996** [comment]
Same issue here, tried with 0.8.7 and still facing this issue, no problem with Monterey and OC 0.8.5
@mrasong Any idea sir.

**Comment by mrasong** [comment]
try to disable wifi in BIOS?

**Comment by vuqn1996** [comment]
Update : I used version to OC 0.8.5 and replaced Airportltlwm.kext of 0.8.7 and installed, but bluetooth is not work.

**Comment by mrasong** [comment]
OC 0.8.5 on Ventura works well except bluetooth ?

**Comment by mrasong** [comment]
try to use the last commit efi from branch master just now.

**Comment by vuqn1996** [comment]
That one is not working for me too, but somehow I just tried to copy 0.8.5 EFI with Airportltlwm.kext of 0.8.7 version, and everything is working well so far. Bluetooth and Wifi also work. Don't know why, but last week when I tried this version, all I got just Bluetooth without wifi and reverse.
![image](https://user-images.githubusercontent.com/35033011/206952246-7fb9c543-1a9a-442c-ba2d-316a9888a49d.png)

**Comment by mrasong** [comment]
I just fixed it yesterday , by using the 085 efi, and rollback some params.

**Comment by vuqn1996** [comment]
Oh really, but I just tried your latest commit, and not worked. I rebooted from my USB which I used to install OS (still have the 0.8.5 that I used before) it suddenly connected to Wifi and Bluetooth.

**Comment by vuqn1996** [comment]
BTW just want to say thank you so much for your hard work with this EFI, you're a time saver for us. I used your EFI since 0.6.6 until now and it's really great.

**Comment by mrasong** [comment]
> I updated Monterey to Ventura and received a prohibitory symbol when using the 0.8.6 EFI.
> 
> What works is 0.8.4 efi with just the AirportItlwm.kext from 0.8.6 EFI.
> 
> https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macos/Big-Sur/macos-big-sur-startup-screen-prohibitory-sign.jpg

Did you get this issue when use the latest commit efi?

**Comment by mrasong** [comment]
> 

If

> Oh really, but I just tried your latest commit, and not worked. I rebooted from my USB which I used to install OS (still have the 0.8.5 that I used before) it suddenly connected to Wifi and Bluetooth.

If you can enter the system successfully, You may use the 085 wifi drive with the 087 EFI

**Comment by mrasong** [comment]
> BTW just want to say thank you so much for your hard work with this EFI, you're a time saver for us. I used your EFI since 0.6.6 until now and it's really great.

My pleasure, I use nuc10 for work too.

**Comment by vuqn1996** [comment]
> If you can enter the system successfully, You may use the 085 wifi drive with the 087 EFI
No, I think it's should be 0.8.5 EFI with 0.8.7 Wifi because I read somewhere you commented that copy Airpotltlwm.kext of 0.8.7 to 0.8.6 so It will work on Ventura, so I tried with 0.8.5 EFI because at that time my Bluetooth is working correctly but Wifi is not. That's weird. Hope that your latest version will help everyone.

**Comment by mrasong** [comment]
Due to the device I have started up normally, I cannot debug for this issue.
1. Use the `v0.8.7.1206` EFI with 085 wifi drive.
2. Try to reset nvram and restart again. 
If this still not work. We know for sure 087 not worked well for some devices.

**Comment by vuqn1996** [comment]
Got it, I will give it a try, Thank you so much.
